professores_ic = [
    "Alan Pedro da Silva",
    "Alejandro César Frery Orgambide",
    "Almir Pereira Guimarães",
    "André Luiz Lins de Aquino",
    "Arturo Hernández Domínguez",
    "Aydano Pamponet Machado",
    "Baldoino Fonseca dos Santos Neto",
    "Bruno Almeida Pimentel",
    "Bruno Costa e Silva Nogueira",
    "Cid Cavalcanti de Albuquerque",
    "Davi Bibiano Brito",
    "Erick de Andrade Barboza",
    "Evandro de Barros Costa",
    "Fábio José Coutinho da Silva",
    "Fábio Paraguaçu Duarte da Costa",
    "Glauber Rodrigues Leite",
    "Ícaro Bezerra Queiroz de Araújo",
    "Ig Ibert Bittencourt Santana Pinto",
    "João Raphael Souza Martins",
    "Jobson de Araújo Nascimento",
    "Leandro Dias da Silva",
    "Leandro Melo de Sales",
    "Leonardo Viana Pereira",
    "Lucas Benevides Viana de Amorim",
    "Marcelo Costa Oliveira",
    "Márcio de Medeiros Ribeiro",
    "Maria Cristina Tenório Cavalcante Escarpini",
    "Mário Hozano Lucas de Souza",
    "Maurício Beltrão de Rossiter Corrêa",
    "Olival de Gusmão Freitas Júnior",
    "Petrúcio Antônio Medeiros Barros",
    "Rafael de Amorim Silva",
    "Ranilson Oscar Araújo Paiva",
    "Rian Gabriel Santos Pinheiro",
    "Roberta Vilhena Vieira Lopes",
    "Rodrigo de Barros Paes",
    "Rodrigo José Sarmento Peixoto",
    "Thales Miranda de Almeida Vieira",
    "Thiago Damasceno Cordeiro",
    "Tiago Alves de Almeida",
    "Tiago Figueiredo Vieira",
    "Willy Carvalho Tiengo",
    "Xu Yang"
]

professores_ic_enfases = {
    "Alan Pedro da Silva": ["Sistemas Inteligentes"],
    "Arturo Hernández Domínguez": ["Sistemas Inteligentes"],
    "Aydano Pamponet Machado": ["Sistemas Inteligentes"],
    "Baldoino Fonseca dos Santos Neto": ["Sistemas Inteligentes"],
    "Bruno Almeida Pimentel": ["Sistemas Inteligentes"],
    "Bruno Costa e Silva Nogueira": ["Sistemas de computação"],
    "Erick de Andrade Barboza": ["Sistemas de computação"],
    "Evandro de Barros Costa": ["Sistemas Inteligentes"],
    "Fábio Paraguaçu Duarte da Costa": ["Sistemas de informação"],
    "Ícaro Bezerra Queiroz de Araújo": ["Sistemas de computação"],
    "Leandro Dias da Silva": ["Sistemas de computação"],
    "Leandro Melo de Sales": ["Sistemas de informação"],
    "Marcelo Costa Oliveira": ["Computação Visual"],
    "Roberta Vilhena Vieira Lopes": ["Sistemas inteligentes"],
    "Rodrigo José Sarmento Peixoto": ["Sistemas de computação"],
    "Thales Miranda de Almeida Vieira": ["Computação Visual"],
    "Thiago Damasceno Cordeiro": ["Sistemas de computação"],
    "Tiago Figueiredo Vieira": ["Computação Visual"],
}